- smb1pdu.c
- smb2pdu.c
- vfs.c
- vfs.h
> cifsd: set inode uid/gid during creation before we unlock it

- cifsacl.c
> cifsd: those should not be cifsd_err-s

- smb2pdu.c
> cifsd: use cpu native to le in rsp

- smb2pdu.c
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>
> cifsd: fix memory leak in smb3_encrypt_resp

- fh.c
- fh.h
- oplock.c
- smb1misc.c
- smb2misc.c
- smb2pdu.c
- vfs.c
Discovered with -Wmissing-prototypes
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> treewide: Add static qualifier to several undeclared functions

- server.c
cifsd: print error in cifsd_set_interfaces() when bind iface is not known to us
> cifsd: print error in cifsd_set_interfaces() when bind iface is not known to us

- smb2pdu.c
- smb2pdu.h
> cifsd: fix double converting preauth hash/cipher id to le

- server.c
> cifsd: check if we have any iface names in startup payload

- transport_tcp.c
> cifsd: use TIMEOUT defines when configuring new socket

- transport_tcp.c
- vfs.c
> cifsd: do not cork/uncork

- oplock.c
- oplock.h
- smb2misc.c
- smb2pdu.c
> cifsd: fix wrong oplock break struct size

- mgmt/user_session.c
> cifsd: log unsupported RPC name

- vfs.c
> cifsd: do not leak .dirent page on cifsd_vfs_kern_path() error

- README.md
> cifsd: update installing prerequisite package for fedora in README

- vfs.c
Cc: Rosen Penev <rosenp@gmail.com>
> cifsd: fix build failure on linux 4.9 kernel

- README.md
> cifsd: update CCM and GCM crypto in README

- vfs.c
Reviewed-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
> cifsd: fix memory leakage from inherit smack patch

- .travis.yml
> cifsd: add smb2 compound test

- .travis.yml
> cifsd: build bin/smbtorture target only

- .travis.yml
- smb1pdu.c
- smb2pdu.c
> cifsd: add one more build target

- smb2pdu.c
> cifsd: smb2_read() frees allocated rbuf in multiple places

- smb2pdu.c
[3-51.9732] [<c0351854>] (depot_fetch_stack) from [<c0185fbc>] (print_track+0x90/0xb4)
[3-51.9732] [<c0185f2c>] (print_track) from [<c0187190>] (print_tracking.part.13+0x3c/0x68)
[3-51.9732]  r6:e5ae1b80 r5:e4501cc0 r4:e195d680
[3-51.9732] [<c0187154>] (print_tracking.part.13) from [<c01872f8>] (print_trailer+0x13c/0x1b8)
[3-51.9732]  r5:e4501cc0 r4:e195d680
[3-51.9732] [<c01871bc>] (print_trailer) from [<c0187448>] (check_bytes_and_report+0xd4/0xf0)
[3-51.9733]  r7:e5ae1b80 r6:e4501cc0 r5:e195d880 r4:e195d884
[3-51.9733] [<c0187374>] (check_bytes_and_report) from [<c01875d0>] (check_object+0x16c/0x234)
[3-51.9733]  r9:e35a6000 r8:e35a7db4 r7:e5ae1b80 r6:000000cc r5:e195d680 r4:e4501cc0
[3-51.9733] [<c0187464>] (check_object) from [<c0187c20>] (free_debug_processing+0x16c/0x344) …
> cifsd: fix memory overrun issue

- smb1pdu.c
> cifsd: add missing cifsd_fd_put at several places in smb1pdu

- glob.h
- server.c
> cifsd: release v2.0.2

- glob.h
> cifsd: release v2.0.3 version

- smb1pdu.c
- smb_common.c
> cifsd: add missing cifsd_fd_put in smb_write_andx

- glob.h
> cifsd: release 2.0.4 version

- .travis.yml
> ksmbd: fix password db file location in travis.yml

- glob.h
> ksmbd: release 3.1.0 version

- README.md
> ksmbd: update README file

- auth.c
- auth.h
- mgmt/ksmbd_ida.c
- mgmt/ksmbd_ida.h
- mgmt/user_session.c
- mgmt/user_session.h
- unicode.c
- unicode.h
- vfs.c
> ksmbd: capsule ifdef CONFIG_SMB_INSECURE_SERVER with smb1 codes

- glob.h
> ksmbd: release 3.1.1 version

- glob.h
> ksmbd: release 3.1.2 version

- glob.h
> ksmbd: release 3.1.3 version

- connection.h
- ksmbd_work.c
- ksmbd_work.h
- server.c
> ksmbd: rework request lock

- glob.h
> ksmbd: release 3.1.4 version

- smb1pdu.c
> ksmbd: fix endian issues in smb1pdu.c

- smb1pdu.c
> ksmbd: fix missing endian conversions in smb1pdu.c

- smb1pdu.c
> ksmbd: use _LE for ATtributes conversion

- smb1pdu.c
- smb1pdu.h
> ksmbd: fix missing endian conversion in smb1pdu.c

- smb1pdu.c
- vfs_cache.c
Cc: Hyunchul Lee <hyc.lee@gmail.com>
> ksmbd: fix fp and ci leakage

- ksmbd_work.h
- smb2pdu.c
> ksmbd: update CreditRequest in last of compound request

- glob.h
- oplock.c
Signed-off-by: Kyeonghwan Jung <kh1123.jung@samsung.com>
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>
> ksmbd: compress two r_count increment lines to single line

- smb2pdu.c
- vfs.c
- vfs.h
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>
> ksmbd: add error handling for kmalloc xattr_stream_name

- README.md
- auth.c
- glob.h
- misc.c
- oplock.c
- oplock.h
- server.c
- smb1misc.c
- smb1ops.c
- smb1pdu.c
- smb1pdu.h
- smb2misc.c
- smb2ops.c
- smb2pdu.c
- smb2pdu.h
- smb_common.c
- smbacl.c
- smbacl.h
- transport_tcp.c
- unicode.c
- vfs.c
- vfs.h
- vfs_cache.c
This reverts commit c1a847731410df15e75ff1b469c4c93d8313d926.
> Revert "ksmbd: downgrade oplock level if file is opened with read only"

- glob.h
The major changes are:
- Fix signing bugs.
- Fix encryption bugs.
- Fix build error on linux-5.8-rc1
- Fix bugs with read-only=yes
- Fix potential stuck issue due to cache buffers exhaustion
> cifsd: release 3.2.1 version

- smb1misc.c
- smb1pdu.c
Hello,
this adds most of the changes which are needed to support some strange old client that I have.
The two patches in here plus the hack from #436 (``conn->use_spnego = false;``) makes everything work for me (at least everything that I tested).
I'm happy for any kind of feedback!
Thank you,
Martin
> Add support for a strange old client that I have
