misc.c
misc.h
smb1pdu.c
smb2pdu.c

extract_sharename() is not very inefficient. For every treename
it does
while (strchr(treename, '\\'))
strsep(&treename, "\\");
So, for example, for treename '\\localhost\IPC$', it scans treename
from the start, finds the first \, invokes strsep(), which scans
treename from the start and updates the treename pointer the position
of the first \. Then it repeats whe whole thing for the second \
and for the last \, until it find the IPC$.
We don't have to do that. We can call strchr() just once, to find
the last \, and be done with the whole thing. No loops, no strsep().

cifsd: rework extract_sharename() and convert_delimiter()

---

smb1pdu.h
smb2pdu.h

Both cpu_to_le32 and cpu_to_le16 are capable to recognize compile
time constant and to avoid runtime overhead of swapXXb. So we can
use them instead of __constant_cpu_to_leXX.
Example:
\#define __swahb32(x)				\
(__builtin_constant_p((__u32)(x)) ?	\
___constant_swahb32(x) :		\
__fswahb32(x))
static __always_inline __u32 __swab32p(const __u32 *p)
{
\#ifdef __arch_swab32p
return __arch_swab32p(p);
\#else
return __swab32(*p);
\#endif
}
static __always_inline __le32 __cpu_to_le32p(const __u32 *p)
{
return (__force __le32)__swab32p(p);
}

cifsd: get rid of __constant_cpu_to_leXX

---

smb2pdu.c

When downloading file through internet browser, windows open stream
file and try to read with big offset and size. It cause read failure
or kernel oops. Need to look into more.
For now, disable stream support at default like samba.

cifsd: disable stream support at default

---

cifsd_server.h
server.c
server.h
transport_ipc.c
transport_tcp.c

Add interfaces parameter to allow connection of specific device in server.
Use match_pattern to consider "eth*" in interfaces.

cifsd: add interfaces parameter

---

smb2pdu.c

cifsd: remove unused store_stream in smb2_open

---

smb2pdu.c

SMB2_FLAGS_RELATED_OPERATIONS and a bunch of other defines are
in cpu_to_le32/16, so are header flags. Casting header flags
to host endianness is not exactly correct:
le32_to_cpu(req->hdr.Flags) & SMB2_FLAGS_RELATED_OPERATIONS
On BE system this will become
BE(flags) & LE(SMB2_FLAGS_RELATED_OPERATIONS)

cifsd: keep header flags in le

---

smb2pdu.c

When commanding df -h, cifs send compound request(open->get_info->close).
But compound_sid is not converted to cpu from le64, So may not get failure
from df -h result.

cifsd: convert compound session id to cpu

---

smb1misc.c

cifsd: not require to convert le in smb1 command

---

vfs_cache.c

Our file-max limits are much lower than INT_MAX, so we can
just use idr_alloc(), idr_alloc_u32() is a bit too much.

cifsd: drop the LINUX_VERSION_CODE from __open_id()

---

unicode.c

When I tried building cifsd against kernel 4.19, I encountered some redefinition errors:
```
CC [M]  /opt/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-03-28-290162b6/unicode.o
In file included from ./arch/arm/include/asm/unaligned.h:12:0,
from ./include/linux/etherdevice.h:28,
from ./include/linux/if_vlan.h:16,
from ./include/linux/filter.h:22,
from ./include/net/sock.h:64,
from /opt/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-03-28-290162b6/glob.h:16,
from /opt/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-03-28-290162b6/unicode.c:14:
./include/linux/unaligned/le_struct.h:7:19: error: redefinition of 'get_unaligned_le16'
static inline u16 get_unaligned_le16(const …
```

cifsd: fix compilation on kernel 4.19

---

smb2pdu.c

Altough smb2 notify is not implemented, we response status pending in smb2
notify. Not sure previous behavior is changed by windows 7 update.
And Rosen reported watching error happen by this code with foobar2000 app.
Cc: Rosen Penev <rosenp@gmail.com>

cifsd: don't send status pending in smb2 notify response

---

smb2ops.c
smb2pdu.c
smb_common.c
transport_tcp.c
transport_tcp.h

[1-176.4036] kcifsd: init_smb2_rsp_hdr:441: conn->credits_granted : 2, credit charge : 16
[1-176.4061] kcifsd: init_smb2_rsp_hdr:441: conn->credits_granted : -14, credit charge : 1
[1-176.4140] kcifsd: smb2_set_rsp_credits:552: credits: requested[0] granted[0] total_granted[-15]
conn->total_credits have been racy since reducing tcp conn lock scope.
This patch change conn->total_credits to atomic variable.

cifsd: fix racy issue after removing cifsd_tcp_conn_lock

---

glob.h
smb2pdu.c
transport_tcp.c

According to the current setup_async_work() operation, a request_entry
can be set in either conn->requests or conn->async_requests.
But, SMB2 CANCEL Request can have both set or not set of
SMB2_FLAGS_ASYNC_COMMAND to cancel the previous async request.
So, add async_request_entry and manage the sync/async list simultaneously.
Signed-off-by: Yunjae Lim <yunjae.lim@samsung.com>

cifsd: add async request entry

---

transport_tcp.c

The prototype of kernel_getpeername was changed
from kernel v4.17
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

cifsd: fix compilation on kernel v4.16

---

oplock.h
smb_common.c

add/remove: 0/0 grow/shrink: 0/9 up/down: 0/-77 (-77)
Function                                     old     new   delta
wait_for_lease_break_ack                     234     231      -3
smb_grant_oplock                            2273    2270      -3
smb_break_all_oplock                         165     162      -3
smb2_oplock_break.cold                       534     531      -3
close_id_del_oplock                          250     247      -3
__smb1_oplock_break_noti                     280     277      -3
smb2_oplock_break                           1118    1112      -6
oplock_break                                1778    1755     -23
smb_break_all_levII_oplock                   428     398     -30
Total: Before=128753, After=128676, chg -0.06%
Signed-off-by: Sergey Senozhatsky …

cifsd: drop several paddings from struct oplock_info

---

transport_tcp.c

Can see:
239 ?        S      0:00 [kcifsd-eth0]
240 ?        S      0:00 [kcifsd-lo]

cifsd: add device name in forker thread name

---

oplock.c
smb2pdu.c
vfs.c
vfs_cache.c
vfs_cache.h

Work in progress. Initial patch for SMB2.
No SMB1 support yet, no durable fp-s handling yet.
Apparently we can have parallel vfs_cache operations
within one connection, cifsd file is not ready for that.
kworker/4:0 CPU 4 kcifsd: __cifsd_close_fd() FD->volatile_id == 0
kworker/0:3 CPU 0 kcifsd: smb2_get_info_file() FD->volatile_id == 0
kworker/0:3 CPU 0 kcifsd: __cifsd_lookup_fd() FD->volatile_id == 0
kworker/0:3 CPU 0 kcifsd: get_file_all_info() FD->volatile_id == 0
kworker/4:0 CPU 4 kcifsd: __cifsd_close_fd() kfree() FD->volatile_id == 0
kworker/0:3 CPU 0 BUG: kernel NULL pointer dereference
[  146.622912] BUG: kernel NULL pointer dereference, address: 000000000000064c
[  146.622915] #PF: supervisor read access in kernel mode
[  146.622919] #PF: error_code(0x0000) - not-present page
[ …

cifsd: add reference count to cifsd_fp

---

smb2pdu.c
vfs_cache.c
vfs_cache.h

APP_INSTANCE_ID durable_handle_context handling performs global ft
lookup with the purpose to do cifsd_close_fd() on found fp. Rework
it and do it in one step, respecting fp's ->refcount value.

cifsd: handle APP_INSTANCE_ID durable_handle_context

---

smb2pdu.c

Before:
[root@localhost ~]# cat /proc/fs/cifs/DebugData
Server interfaces: 1
0)	Speed: 1000000000 bps
Capabilities:
IPv4: 47.1.30.172
After:
[root@localhost ~]# cat /proc/fs/cifs/DebugData
Server interfaces: 1
0)	Speed: 1000000000 bps
Capabilities:
IPv4: 172.30.1.47

cifsd: reverse ipv4 address in NETWORK INTERFACE INFO response

---

smb2pdu.c

the FSCTL_SRV_COPYCHUNK response must include
the SRV_COPYCHUNK_RESPONSE payload even if the request fails.
Without this, some of smbtortures testcases will fail.
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

cifsd: resolve some failing copychunk testcases of smbtorture

---

smb2pdu.c

Fix copy_file_range failure.
Allow FSCTL_SRC_COPYCHUNK_WRITE even when the destination
file has not only write accesses but read accesses.
Windows clients seem to allow this and smbtorture does not
complain about this.
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

cifsd: fix xfstests generic/263 failure

---

smb2pdu.c

Window 7 sometimes send the enum share all request using smb2 ioctl.
The old code of FSCTL_PIPE_TRANSCEIVE has a problem that allows
the request only when tree id is 0. The tree id does not have to be zero.
Now remove wrong code and solve the problem.

cifsd: fix share enum failure issue with windows 7

---

crypto_ctx.c

If crypto module is missing, kernel oops could happen.
[0-203.1363] [<bf063bcc>] (____crypto_shash_ctx_find [cifsd]) from [<bf063dc8>] (cifsd_crypto_ctx_find_sha512+0x14/0x1c [cifsd])
[0-203.1363]  r7:d6beb400 r6:c232a000 r5:000000ae r4:dc8e0900
[0-203.1364] [<bf063db4>] (cifsd_crypto_ctx_find_sha512 [cifsd]) from [<bf054ab4>] (cifsd_gen_preauth_integrity_hash+0x38/0xd8 [cifsd])
[0-203.1364] [<bf054a7c>] (cifsd_gen_preauth_integrity_hash [cifsd]) from [<bf067258>] (smb2_handle_negotiate+0x51c/0x7f0 [cifsd])
[0-203.1364]  r9:00000000 r8:d6beb400 r7:00000000 r6:c232a000 r5:d5479440 r4:dc8e0900
[0-203.1365] [<bf066d3c>] (smb2_handle_negotiate [cifsd]) from [<bf05f490>] (cifsd_smb_negotiate_common+0xe8/0x10c [cifsd])
[0-203.1365]  r10:bf084464 r9:bf05ec1c r8:bf0666f8 r7:c232a050 r6:00000000 …

cifsd: check crypto API error using IS_ERR

---

connection.c
server.c
transport_tcp.c

Cc: Andy Walsh <andy.walsh44@gmail.com>

cifsd: set zero to rcv and snd timeout before socket shutdown

---

connection.c
smb1pdu.c

If server give short filename information to client, client could try
to access using short name. That cause file creation failure while
firefox start running on cifsd share.

ksmbd: don't give shortname in smb1 find_first/next

---

mgmt/user_session.c

If a new connection is made after kill_server, the old share configuration
can be used by using the previous tree id.
It can cause unintended configuration operation (follow symlink=yes/no)
Clear shares in tree list when kill_server is called
Reported-by: Fredrik Ternerot <fredrikt@axis.com>

ksmbd: clear shares in session destroy when kill_server is called

---

smb2pdu.c

ksmbd: downgrade oplock level if file is opened with read only

---

glob.h

- Fix sparse warnings.
- Fix warnings from checkpatch.pl.
- Add cifsd.rst Documentation file.
- Downgrade some error print to debug print.

ksmbd: release 3.1.9 version

---

smb2pdu.c
vfs.c
vfs.h

Re-implement FSCTL_QUERY_ALLOCATED_RANGES using SEEK DATA/HOLE.
This can be implemented simpler than the implementation using existing
fiemap and fix generic/476 failure.

ksmbd: use SEEK DATA/HOLE for FSCTL_QUERY_ALLOCATED_RANGES ioctl

---

glob.h

- fix xfstests issues
- cleanup codes for cifsd upstream
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

ksmbd: release 3.2.0 version

---

server.c
smb1pdu.c
smb1pdu.h
smb2pdu.c
smb2pdu.h
smb_common.h

When signing is mandatory by server configuration, include required
signing also in first negotiation response when upgrading from SMB1 to
SMB2 in auto-negotiation.
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>

ksmbd: include required signing in auto-negotiation response

---

glob.h
server.c

Make sure work->sess is not NULL when calling check_sign_req() to
prevent NULL pointer dereference. This was causing kernel panic when
using signing and pysmb (SMB1) as client.
Fixes: c670a9a0d35f ("ksmbd: verify and set signature for compound request/response")
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>

cifsd: prevent NULL pointer dereference in signing handling

---

glob.h

Major changes are:
- rework SMB2_RETURN_SINGLE_ENTRY in smb2_query_dir
- fix stuck issue while writing files with windows client

cifsd: release 3.2.3 version

---

glob.h

Major changes are:
- Fix the connection failures when giving -m and -e option with smbclient.
- Fix copy failure with local filesystem that doesn't support
fallocate.
- Fix negotiation failure when setting same a dialect to server min/max
protocl parameter.

cifsd: release 3.2.4 version

---

smb1pdu.c

The SMB header has a flag and flags2 field where the client sends the
capabilities that it supports. The server is then supposed to respond to
this accordingly.
When bit 11 is set in flags2 then "Extended Security Negotiation" is
enabled. In this case we are supposed to use spnego. When that field is
absent however spnego should be disabled.
The samba server for example does this:
if (req->smb_conn->negotiate.encrypted_passwords &&
(req->flags2 & FLAGS2_EXTENDED_SECURITY))
negotiate_spnego = true;
Fixes #436 for me

cifsd: make spnego depend on the "extended security" bit in flags2

---

smb1pdu.c

For most errors the find_next() implementation jumps to the err_out
label. This unconditionally calls kfree(d_info.smb1_name). Use memset()
to zero-out the struct ksmbd_dir_info d_info variable at the beginning
of the function so when any error occurs d_info.smb1_name will either be
NULL or have a valid pointer in it.
This fixes a crash which was observed in kmem_cache_free_bulk() -
presumably because the code was trying to free memory from an address
which was just garbage (non-initialized) data from the stack.
Fixes #440 for me

Initialize d_info in smb1pdu find_next()

---

smb1pdu.c

dir_fp is already free by ksmbd_close_fd() before ksmbd_fd_put().
Remove unneeded ksmbd_fd_put().
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

cifsd: remove unneeded ksmbd_fd_put() in find_next()

---

smb2pdu.c

If you use the ls command in directory containing the pipe file
through the cifs client, There is an issue that is blocked in
dentry_open(). The file open is blocked if openning with O_RDONLY.
cifs client calls smb2 open after query dirty for the smb2 get info,
and blocking in smb2_open occurs. There is no need to block from
smb2 open on the server. blocking for pipe file will have to be done
by the client.

cifsd: open file with O_NONBLOCK flags by default

---

glob.h

Major changes are:
- Add ACLs support
- Add Kerberos support
- Add query info/query dir/statfs for smb3.1.1 posix extension.
- Fix warnings from checkpatch.pl
- Fix racy issue reported and warnings from KSAN by OpenWRT.

cifsd: release 3.3.0 version

---

glob.h

Major change are:
- Fix insmod failure if CONFIG_FS_POSIX_ACL is not set in config.

cifsd: release 3.3.1 version

---

glob.h

The major changes are:
- Fix some of xfstests tests failures when actimeo=0 mount option
is not used in local.config of xfstests.
- WSL reparse tags support for special files.
- Fix several permission issues.
- Set O_PATH and O_NONBLOCK flags to open_flags.

cifsd: release 3.3.2 version

---

glob.h

Major changes are:
- add support for SMB3 multichannel.
- add support for FSCTL_DUPLICATE_EXTENTS_TO_FILE.
- add support for AES256 encryption.
- rename cifsd to ksmbd.
- use generic asn1 decoder instead of own one.
- remove cache read/trans buffer feature.
- fix several bugs.
- cleanup codes from review comments.

ksmbd: release 3.4.0 version
